[package]
name = "private-semgrep-registry"
version = "0.1.0"
edition = "2021"

[dependencies]
semgrep-rs = { git = "https://github.com/parsiya/semgrep-rs", branch = "dev" }

serde_yaml = "0.9"
serde = {version = "1.0"}