# create a release when a new tag is created.

name: Release from tag
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true # populate semgrep-rs
      # based on https://github.com/timabell/gitopolis/blob/main/.github/workflows/_release.yml
      - name: Setup
        run: cargo install -f cross
      - name: Build-linux
        run: cross build --target x86_64-unknown-linux-gnu --release
      - name: Build-win
        run: cross build --target x86_64-pc-windows-gnu --release
      - name: Package Linux
        run: tar -czvf personal-semgrep-server-linux-x86_64.tar.gz -C target/x86_64-unknown-linux-gnu/release/ personal-semgrep-server
      - name: Package Windows
        run: zip personal-semgrep-server-windows-x86_64.zip target/x86_64-pc-windows-gnu/release/personal-semgrep-server.exe
      - name: Publish
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          artifacts: personal-semgrep-server-linux-x86_64.tar.gz,personal-semgrep-server-windows-x86_64.zip
          token: ${{ secrets.GITHUB_TOKEN }}
      # - name: Build-darwin-x64 # TODO
      # - name: Build-darwin-arm # TODO