# Build nad upload binaries when a release is published.
name: Release
on:
  release:
    types: [published] 
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-apple-darwin, x86_64-unknown-linux-musl]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true # populate src/semgrep-rs
      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@v1.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}